### ISSUE TITLE
Parameter file example

### ISSUE THREAD

**Issue by iquasere** [PNNL-Comp-Mass-Spec/Protein-Digestion-Simulator#1]
Greetings!

I have tried to use this tool for simulating MS data, but so far have not been successfully. Trying to use it through the GUI, it always crashes, and through the CLI I need a parameters file, and I can't find anywhere an example of such file.

Is there some way of saving the parameters set through the GUI for use in the CLI?

Thank you for your attention!

**Comment by alchemistmatt** [comment]
What operating system are you using?  It shouldn't be crashing; it should work fine with 32-bit and 64-bit Windows 7, 8, or 10.  You can run it on Linux using [Mono,](https://www.mono-project.com/docs/about-mono/supported-platforms/linux/) but in that case you should stick with the CLI mode.

Also, this program does not simulate MS data; its primary purpose is to manipulate FASTA files (including converting to/from tab-delimited text).

Yes, the GUI has an option to save a parameter file; it's under the File menu.  I did this, and added an example parameter file named `ProteinDigestionSimulatorOptions.xml` to the repository; see
https://github.com/PNNL-Comp-Mass-Spec/Protein-Digestion-Simulator/tree/master/Docs

**Comment by iquasere** [comment]
Thank you for the help!
